### PR TITLE
Sdk2 (old motion sensor support)

### PR DESCRIPTION
**Pull request by phgmhendrix**
I have added support for the K-940 MCW motion sensor.
While at it I also added the flood sensor to the list but no complete support yet.

### CODE REVIEW

**Comment by phgmhendrix** [comment]
I Think I need to revise the type of the flood sensor. 6a is a smoke detector in my setup, but at a colleague it seems to be a flood sensor.
Will get back on that.

**Comment by nlrb** [comment]
Thanks for the addition. How many data point do you have to confirm that '1a' is always a K-940 MCW? From that data I have from lots of panels, the most significant nibble is not part of the sensor type for PowerMax models.

**Comment by phgmhendrix** [comment]
My colleague and I built a Windows IoT application based on a lot of information and puzzle pieces.
Currently I have two of these sensors that show up this way.

I know that one other colleague also experiences the same issue. I can ask him if he would like to test what his results are.

We have programmed everything based on reverse engineering and the links below.
http://www.domoticaforum.eu/viewtopic.php?f=68&t=6581
http://www.domoticaforum.eu/viewtopic.php?f=68&t=7152&hilit=powermax+serial+pinout
http://code.mios.com/trac/mios_visonic-powermax#
http://forum.micasaverde.com/index.php?topic=6884.0
(volgens mij allemaal erg bekend bij jou :) )

So far we came up with the types in the attachement (that mostly match your implementation).

[SensorType.cs.txt](https://github.com/nlrb/com.visonic.powermax/files/3439344/SensorType.cs.txt)
Sensor

**Comment by nlrb** [comment]
Thanks,, that is an interesting list :-). And yes, that reference material looks very familiar ;-).

I've gone through some old logs, and these are the byte IDs I've come across in the past:
/0C *
/6A ?
6B
6F
75 *
76 *
85 *
86
87
93 *
95 *
96 *
97 *
9A *
C3 *
C4 
D3 *
D4 *
/D5 *
E3 *
E4 *
F3
F4
FA *
/FB *
FF *

The ones prefixed with a slash are new to me, the ones with a * you have identified the type. So that are most of them, except for 6f, 86, 87, c4, f3, f4. Let's see if we can identify these as well and make the implementation the same as for the PowerMaster. Id '6b' I can confirm myself as MCT-442.

**Comment by nlrb** [comment]
BTW:

- 6a is a MCT-425 smoke sensor
- e3 is a Next K9-85 MCW

**Comment by phgmhendrix** [comment]
@nlrb : is there logging available so I can analyze PDU's and messages?
~~I want to analyse some stuff because most of the time I don't receive any notifications in Homey when a user arms or disarms the alarm. However sometimes it seems to work.
I want to pinpoint what is going on.~~
_Nevermind, I was missing that the arm-signal only happens after 'exit delay' and only when the state really changes... so siarming when not armed does not trigger the event._

**Comment by nlrb** [comment]
Hi Peter,
If you run the app with `athom app run` instead of `install` you should see all debug logging incl. PDUs.

**Comment by phgmhendrix** [comment]
> Hi Peter,
> If you run the app with athom app run instead of install you should see all debug logging incl. PDUs.

Thanks, I was indeed already running it to a logfile the generate some logging to examine further.

**Pull request closed without merging**
